### ISSUE TITLE
Great job! 🎉 

### ISSUE THREAD

**Issue by fi-ya** [fac22/week3-BDJS#31]
Well done in hosting your project on Heroku! 🥳 
I was able to sign up and see my order as well as delete it and had errors handled with user not found! 👏🏾 
Also excellent work as you were able to to velocity & actuals! This will help you manage your time in the up coming weeks. 
Well done in co-authoring, and getting your commits near enough even. 
Your code is modularised and you managed to get some cypress tests done!
Pat your selves on the back!

**Comment by jijip41** [comment]
Thank you for your review! 💝
